In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/zomato_data.csv")
print(df.shape)

(51717, 15)

In [3]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  listed_in(type)              51717 non-null  object
 14  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(14)
memory usage: 5.9+ MB

In [5]:
df.dtypes

url                            object
address                        object
name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
phone                          object
location                       object
rest_type                      object
dish_liked                     object
cuisines                       object
approx_cost(for two people)    object
listed_in(type)                object
listed_in(city)                object
dtype: object

In [6]:
pd.DataFrame({
    "Missing" : df.isnull().sum(),
    "Missing_pct" : (df.isnull().mean()*100).round(2)
})

                             Missing  Missing_pct
url                                0         0.00
address                            0         0.00
name                               0         0.00
online_order                       0         0.00
book_table                         0         0.00
rate                            7775        15.03
votes                              0         0.00
phone                           1208         2.34
location                          21         0.04
rest_type                        227         0.44
dish_liked                     28078        54.29
cuisines                          45         0.09
approx_cost(for two people)      346         0.67
listed_in(type)                    0         0.00
listed_in(city)                    0         0.00

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.nunique()

url                            51717
address                        11495
name                            8792
online_order                       2
book_table                         2
rate                              64
votes                           2328
phone                          14926
location                          93
rest_type                         93
dish_liked                      5271
cuisines                        2723
approx_cost(for two people)       70
listed_in(type)                    7
listed_in(city)                   30
dtype: int64

In [9]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [10]:
for col in ["online_order","book_table","listed_in(type)"]:
  print(df[col].value_counts(dropna=False),'\n')

online_order
Yes    30444
No     21273
Name: count, dtype: int64

book_table
No     45268
Yes     6449
Name: count, dtype: int64

listed_in(type)
Delivery              25942
Dine-out              17779
Desserts               3593
Cafes                  1723
Drinks & nightlife     1101
Buffet                  882
Pubs and bars           697
Name: count, dtype: int64

In [11]:
df["rest_type"].value_counts().head(10)

rest_type
Quick Bites           19132
Casual Dining         10330
Cafe                   3732
Delivery               2604
Dessert Parlor         2263
Takeaway, Delivery     2037
Casual Dining, Bar     1154
Bakery                 1141
Beverage Shop           867
Bar                     697
Name: count, dtype: int64

In [12]:
df["cuisines"].value_counts().head(10)

cuisines
North Indian                           2913
North Indian, Chinese                  2385
South Indian                           1828
Biryani                                 918
Bakery, Desserts                        911
Fast Food                               803
Desserts                                766
Cafe                                    756
South Indian, North Indian, Chinese     726
Bakery                                  651
Name: count, dtype: int64

In [13]:
df["rate"].value_counts(dropna=False).head(15)

rate
NaN       7775
NEW       2208
3.9/5     2098
3.8/5     2022
3.7/5     2011
3.9 /5    1874
3.8 /5    1851
3.7 /5    1810
3.6/5     1773
4.0/5     1609
4.0 /5    1574
3.6 /5    1543
4.1/5     1474
4.1 /5    1474
3.5/5     1431
Name: count, dtype: int64

In [14]:
df["approx_cost(for two people)"].tail(10)

51707    2,000
51708    1,200
51709      800
51710      900
51711      800
51712    1,500
51713      600
51714    2,000
51715    2,500
51716    1,500
Name: approx_cost(for two people), dtype: object

In [15]:
df[df["name"] == "Hammered"][["name", "votes", "listed_in(type)", "listed_in(city)"]].head(10)

           name  votes     listed_in(type) listed_in(city)
5103   Hammered   4639               Cafes    Brigade Road
5184   Hammered   4657            Delivery    Brigade Road
5930   Hammered   4657            Desserts    Brigade Road
6529   Hammered   4657            Dine-out    Brigade Road
6660   Hammered   4657  Drinks & nightlife    Brigade Road
6739   Hammered   4657       Pubs and bars    Brigade Road
11669  Hammered   4677               Cafes   Church Street
11736  Hammered   4677            Delivery   Church Street
12486  Hammered   4677            Desserts   Church Street
13056  Hammered   4677            Dine-out   Church Street

In [17]:
df[df["name"].str.contains(r"[^\x00-\x7F]", na=False)]["name"].head()

10       CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
193      CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
566      CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
974        Bohra Bohra CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
1303           Foreign CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
                               ...
48774    KazÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
49053    Foreign CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
49449    Mint Spice CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
49941    Mint Spice CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
50387    Foreign CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
Name: name, Length: 269, dtype: object

In [18]:
df["phone"].str.contains(r"\r\n", na=False).sum()

np.int64(12492)

In [19]:
((df["rate"].isna()) & (df["votes"] == 0)).sum()

np.int64(7731)